config/routes.rb
SueGlobal::Application.routes.draw do
  get "university_users/index"

  get "university_users/destroy"

  filter :locale, :pagination

  get 'index/confirm/:slug', to: 'index_confirmation#confirm', as: :index_confirm
  get 'index/reject/:slug', to: 'index_confirmation#reject', as: :index_reject
  get "annual_report/:type/(:year)", to: 'annual_report#show', as: :annual_resume

  get "summary/(:year)", to: 'summary#index', as: :summary

  resources :journals
  resources :annual_reports

  get "/pages/:id" => "pages#show", as: :page, format: false
  get "accept_change_request/:token", to: "university_change_request#accept", as: "accept_change_request"

  resources :announcements

  resources :sources
  resources :indices do
    resources :samples, shallow: true
  end
  resources :segmentation_variables, except: [:destroy] do
    resources :segments, only: [:new, :create]
  end

  resources :password_resets, only: [:create, :update, :edit]
  resources :user_sessions

  match 'login' => 'user_sessions#new', as: :login
  match 'logout' => 'user_sessions#destroy', as: :logout

  get 'signup' => 'users#new', as: 'signup'
  resources :users do
    member do
      get :activate, as: :activate
      get :roles, as: :roles, to: 'users#roles'
      post :roles, as: :roles, to: 'users#set_roles'
    end
  end

  get 'studies/:type', to: 'studies#show', as: 'studies_by_type'
  get 'studies/:type/annual_report/(:year)', to: 'annual_report#show', as: 'studies_annual_report'
  get 'activities/search', to: 'activities#search', as: 'activities_search'
  post 'activities/search', to: 'activities#retrieve', as: 'activities_search'
  resources :universities do
    resources :services, shallow: true, except: :show
    resources :achieved_activities, shallow: true
    resources :general_frames, shallow: true do
      collection do
         get 'evolution', as: :evolution
      end
    end

    resources :student_studies, shallow: true
    resources :employer_studies, shallow: true
    resources :public_source_studies, shallow: true
    resources :agreement_source_studies, shallow: true
    resources :database_studies, shallow: true
    resources :other_studies, shallow: true

    resources :users,  only: [:index, :destroy], controller: 'university_users'

    member do
      get 'add_user'
      post 'add_user', action: 'do_add_user'
    end
  end

  root to: 'pages#show', id: 'home'

end

app/controllers/announcements_controller.rb
# -*- encoding : utf-8 -*-
class AnnouncementsController < ApplicationController
  load_and_authorize_resource
  before_filter :require_login

  # GET /announcements
  # GET /announcements.json
  def index
    @announcements = Announcement.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @announcements }
    end
  end

  # GET /announcements/1
  # GET /announcements/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @announcement }
    end
  end

  # GET /announcements/new
  # GET /announcements/new.json
  def new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @announcement }
    end
  end

  # GET /announcements/1/edit
  def edit
  end

  # POST /announcements
  # POST /announcements.json
  def create
    respond_to do |format|
      if @announcement.save
        format.html { redirect_to @announcement, notice: 'Announcement was successfully created.' }
        format.json { render json: @announcement, status: :created, location: @announcement }
      else
        format.html { render action: "new" }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /announcements/1
  # PUT /announcements/1.json
  def update
    respond_to do |format|
      if @announcement.update_attributes(params[:announcement])
        format.html { redirect_to @announcement, notice: 'Announcement was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /announcements/1
  # DELETE /announcements/1.json
  def destroy
    @announcement = Announcement.find(params[:id])
    @announcement.destroy

    respond_to do |format|
      format.html { redirect_to announcements_url }
      format.json { head :no_content }
    end
  end
end

app/views/announcements/_form.html.erb
<%= simple_form_for(@announcement) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :body, input_html: {rows: 4} -%>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/announcements/edit.html.erb
<h1>Editing announcement</h1>

<%= render 'form' %>

<%= link_to 'Show', @announcement %> |
<%= link_to 'Back', announcements_path %>

app/views/announcements/index.html.erb
<h1>Listing announcements</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @announcements.each do |announcement| %>
  <tr>
    <td><%= link_to 'Show', announcement %></td>
    <td><%= link_to 'Edit', edit_announcement_path(announcement) %></td>
    <td><%= link_to 'Destroy', announcement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Announcement', new_announcement_path %>

app/views/announcements/new.html.erb
<h1>New announcement</h1>

<%= render 'form' %>

<%= link_to 'Back', announcements_path %>

app/views/announcements/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_announcement_path(@announcement) %> |
<%= link_to 'Back', announcements_path %>