config/routes.rb
SueGlobal::Application.routes.draw do
  get "university_users/index"

  get "university_users/destroy"

  filter :locale, :pagination

  get 'index/confirm/:slug', to: 'index_confirmation#confirm', as: :index_confirm
  get 'index/reject/:slug', to: 'index_confirmation#reject', as: :index_reject
  get "annual_report/:type/(:year)", to: 'annual_report#show', as: :annual_resume

  get "summary/(:year)", to: 'summary#index', as: :summary

  resources :journals
  resources :annual_reports

  get "/pages/:id" => "pages#show", as: :page, format: false
  get "accept_change_request/:token", to: "university_change_request#accept", as: "accept_change_request"

  resources :announcements

  resources :sources
  resources :indices do
    resources :samples, shallow: true
  end
  resources :segmentation_variables, except: [:destroy] do
    resources :segments, only: [:new, :create]
  end

  resources :password_resets, only: [:create, :update, :edit]
  resources :user_sessions

  match 'login' => 'user_sessions#new', as: :login
  match 'logout' => 'user_sessions#destroy', as: :logout

  get 'signup' => 'users#new', as: 'signup'
  resources :users do
    member do
      get :activate, as: :activate
      get :roles, as: :roles, to: 'users#roles'
      post :roles, as: :roles, to: 'users#set_roles'
    end
  end

  get 'studies/:type', to: 'studies#show', as: 'studies_by_type'
  get 'studies/:type/annual_report/(:year)', to: 'annual_report#show', as: 'studies_annual_report'
  get 'activities/search', to: 'activities#search', as: 'activities_search'
  post 'activities/search', to: 'activities#retrieve', as: 'activities_search'
  resources :universities do
    resources :services, shallow: true, except: :show
    resources :achieved_activities, shallow: true
    resources :general_frames, shallow: true do
      collection do
         get 'evolution', as: :evolution
      end
    end

    resources :student_studies, shallow: true
    resources :employer_studies, shallow: true
    resources :public_source_studies, shallow: true
    resources :agreement_source_studies, shallow: true
    resources :database_studies, shallow: true
    resources :other_studies, shallow: true

    resources :users,  only: [:index, :destroy], controller: 'university_users'

    member do
      get 'add_user'
      post 'add_user', action: 'do_add_user'
    end
  end

  root to: 'pages#show', id: 'home'

end

app/models/sample.rb
# -*- encoding : utf-8 -*-
class Sample < ActiveRecord::Base
  belongs_to :index
  belongs_to :periodicity
  belongs_to :source
  has_and_belongs_to_many :segments
  has_many :sample_values
  accepts_nested_attributes_for :sample_values
  attr_accessible :methodology_url, :taken_at, :sample_values_attributes
  accepts_nested_attributes_for :periodicity
  attr_accessible :periodicity_attributes

  def can_edit_header?
    new_record? || (Time.zone.now - created_at) < 15.minutes
  end

  def value_for *variables
    value = sample_values.find do |sv|
      variables.all? do |v|
        sv.segmentation_variable_values.include? v
      end
    end

    value || new_value_for(*variables)
  end

  def new_value_for *variables
    SampleValue.new.tap do |s|
      s.sample = self
      s.segmentation_variable_values.push *variables
    end
  end

  def interval
    periodicity_type = periodicity.periodicity_type.to_sym
    case periodicity_type
    when :no_periodicity
      single_date_interval
    when :other
      single_date_interval
    when :monthly
      single_date_interval
    else
      two_dates_interval
    end
  end

  class << self
    def from_index index
      Sample.new.tap do |obj|
        obj.source = index.source
        obj.periodicity = index.periodicity
        obj.methodology_url = index.methodology_url
        obj.index = index
        obj.segments = index.segments
      end
    end
  end

  extend FriendlyId
  friendly_id :name_for_slug, use: :slugged

  def should_generate_new_friendly_id?
    new_record? || self[:slug].blank?
  end

  def name_for_slug
    "#{index.name} #{taken_at.strftime('%d-%m-%Y')}"
  end

  def to_key
    [slug]
  end

  protected
  def format_date(date)
    date.strftime('%m-%Y')
  end

  def single_date_interval
    "#{format_date(taken_at)} (#{Periodicity.translate_option(periodicity.periodicity_type)})"
  end

  def two_dates_interval
    "#{format_date(taken_at)} - #{format_date(taken_at + periodicity.as_time - 1.month)}"
  end
end

app/controllers/samples_controller.rb
# -*- encoding : utf-8 -*-
class SamplesController < ApplicationController
  before_filter :require_login, except: [:index, :show]

  load_and_authorize_resource :index, except: [:index, :show], find_by: :slug
  load_and_authorize_resource :sample, except: [:index, :show, :create], through: :index,
    shallow: true, singleton: true, find_by: :slug

  before_filter :add_index_breadcrumb, except: [:index, :show, :edit, :update, :create]
  before_filter :add_ordered_variables, only: [:new, :create, :edit, :update]
  # GET /samples
  # GET /samples.json
  def index
    @index = Index.find_by_slug(params[:index_id])
    @samples = @index.samples
    add_index_breadcrumb

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @samples }
    end
  end

  # GET /samples/1
  # GET /samples/1.json
  def show
    @sample = Sample.find_by_slug params[:id]
    @index = @sample.index
    add_index_breadcrumb
    add_sample_breadcrumb
    add_ordered_variables
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sample }
    end
  end

  # GET /samples/new
  # GET /samples/new.json
  def new
    @sample = Sample.from_index @index
    add_ordered_variables
    @path = [@index, @sample]
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sample }
    end
  end

  # GET /samples/1/edit
  def edit
    @index = @sample.index
    add_index_breadcrumb
    add_sample_breadcrumb
    add_ordered_variables
    @path = @sample
  end

  # POST /samples
  # POST /samples.json
  def create
    @sample = Sample.from_index @index
    set_time
    set_periodicity
    create_values_for(@sample, params[:sample][:sample_values_attributes])
    respond_to do |format|
      if @sample.save
        format.html { redirect_to @sample, notice: t2('create.notice')}
        format.json { render json: @sample, status: :created, location: @sample }
      else
        format.html { render action: "new" }
        format.json { render json: @sample.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /samples/1
  # PUT /samples/1.json
  def update
    set_time
    set_periodicity
    update_values_for(params[:sample][:sample_values_attributes])
    respond_to do |format|
      if @sample.save
        format.html { redirect_to @sample, notice: t2('update.notice')}
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sample.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /samples/1
  # DELETE /samples/1.json
  def destroy
    @sample = Sample.find(params[:id])
    @index = @sample.index
    @sample.destroy

    respond_to do |format|
      format.html { redirect_to index_samples_url(@index), notice: t2('destroy.notice') }
      format.json { head :no_content }
    end
  end

  protected

  def create_values_for sample, values
    values.each_pair do |_, value|
      SampleValue.new do |v|
        v.segmentation_variable_value_ids = value[:segmentation_variable_value_ids]
        v.value_in_cents = value_for_param value
        sample.sample_values << v
      end
    end
  end

  def value_for_param value
    if value[:value].blank?
      nil
    else
      convert_to_fixnum value[:value]
    end
  end

  def convert_to_fixnum val
    return val.to_i * 100 unless val.include? '.'
    val = val + "00"
    val.match(/\d+\.\d{2}/).to_a.first.gsub('.','').to_i
  end

  def update_values_for values
    values.each_pair do |key,value|
      SampleValue.find_by_id(key).tap do |v|
        v.value_in_cents = value_for_param value
        v.save
      end
    end
  end

  def set_time
    if @sample.can_edit_header? &&
      params[:sample][:"taken_at(1i)"].present? &&
      params[:sample][:"taken_at(2i)"].present? &&
      params[:sample][:"taken_at(3i)"].present?

      @sample.taken_at = Time.utc params[:sample][:"taken_at(1i)"],params[:sample][:"taken_at(2i)"],params[:sample][:"taken_at(3i)"]
    end
  end

  def set_periodicity
    if @sample.can_edit_header? &&
      params[:sample][:periodicity_attributes][:periodicity_type].present?

      @sample.periodicity.periodicity_type = params[:sample][:periodicity_attributes][:periodicity_type]
    end
  end


  def add_index_breadcrumb
    add_breadcrumb @index.name, index_path(@index)
  end

  def add_sample_breadcrumb
    add_breadcrumb @sample.taken_at.strftime('%m-%Y'), sample_path(@sample)
  end

  def add_ordered_variables
    @ordered_variables = OrderedVariables.new @sample
  end

  def t2 path
    I18n.t path, scope: 'controllers.samples'
  end
end

app/helpers/samples_helper.rb
# -*- encoding : utf-8 -*-
module SamplesHelper
end

app/views/samples/_form.html.erb
<%= simple_form_for(@path) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">


    <% if @sample.can_edit_header? %>

      <%= f.simple_fields_for(:periodicity) do |periodicity_builder| %>
        <%= periodicity_builder.input :periodicity_type,
          collection: Periodicity.select_options_without_other,
          include_blank: false %>
      <% end -%>
      <%= f.input :taken_at, as: :date,
        discard_day: true,
        order: [:month, :year],
        end_year: Time.now.year %>
    <% else -%>
      <%= render partial: 'periodicity', object: @sample.periodicity %>
      <%= @sample.interval %>
    <% end -%>

    <table class="sample-table table">
      <thead>
        <tr>
          <% @ordered_variables.rest_row_variables.each do |rv| -%>
            <th><%= rv.name %></th>
          <% end -%>
          <th><%= @ordered_variables.main_row_variable.name %></th>
          <% @ordered_variables.column_variable_values.each do |val| -%>
            <th><%= val.value %></th>
          <% end -%>
        </tr>
      </thead>
      <tbody>
        <% i =0 -%>
        <% @ordered_variables.complete_table.each do |row| -%>
          <tr>
            <% row.each do |val| -%>
              <td>
                <% if val.is_a? SampleValue -%>
                  <%= f.simple_fields_for "sample_values_attributes[#{val.persisted? ? val.id : i}]", val do |builder| %>
                    <%= render 'sample_value_form', f: builder %>
                    <% i = i + 1 %>
                  <% end -%>
                <% else %>
                  <%= val.value %>
                <% end -%>
              </td>
            <% end -%>
          </tr>
        <% end -%>
      </tbody>
    </table>
  </div>

  <div class="form-actions">
    <% if @sample.new_record? -%>
      <p style="color: #c09853" class="text-warning"><%= t '.correct_data' %></p>
    <% end -%>

    <%= f.button :submit %>
  </div>
<% end %>

app/views/samples/_sample_value_form.html.erb
<% if f.object.new_record? -%>
  <% f.object.segmentation_variable_values.each do |value| -%>
    <%= f.hidden_field "segmentation_variable_value_ids][", value: value.id %>
  <% end -%>
<% end -%>
<%= f.input :value, as: :string, label: false, wrapper: :too_many_inputs  %>

app/views/samples/index.html.erb
<h1>
  <%= t '.header', index: @index.name %>
  <% if can? :new, Sample -%>
    <%= new_link new_index_sample_path(@index) %>
  <% end -%>
</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th><%= Sample.human_attribute_name :taken_at %></th>
      <th><%= t '.actions' %></th>
    </tr>
  </thead>

  <tbody>
    <% @samples.each do |sample| %>
      <tr>
        <td><%= link_to sample.interval, sample %></td>
        <td>
          <% if can? :edit, sample -%>
            <%= edit_link edit_sample_path(sample) %>
          <% end -%>
          <% if can? :destroy, sample -%>
            <%= destroy_link sample, method: :delete, data: { confirm: t('.destroy_confirmation')} %></td>
        <% end -%>
      </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to_if can?(:new, Sample), t('.new_sample'), new_index_sample_path(@index), :class => 'btn' do "" end %>

app/views/samples/show.html.erb
<h2>
  <%= t '.header', index: @sample.index.name %>
  <% if can? :edit, @sample -%>
    <%= edit_link edit_sample_path(@sample) -%>
  <% end -%>
</h2>

<div class="field">
  <span class="data-label"><%= t '.period' %></span>
  <span class="data"><%= @sample.interval %></span>
</div>
<div class="field">
  <span class="data-label"><%= Source.model_name.human count: 1 %></span>
  <span class="data"><%= @sample.source.name %></span>
</div>
<div class="field">
  <span class="data-label"><%= Sample.human_attribute_name :methodology_url %></span>
  <span class="data"><%= link_to t('link'), @sample.methodology_url %></span>
</div>
<table class="table">
  <thead>
    <tr>
      <% @ordered_variables.rest_row_variables.each do |rv| -%>
        <th><%= rv.name %></th>
      <% end -%>
      <th><%= @ordered_variables.main_row_variable.name %></th>
      <% @ordered_variables.column_variable_values.each do |val| -%>
        <th><%= val.value %></th>
      <% end -%>
    </tr>
  </thead>
  <tbody>
    <% @ordered_variables.complete_table.each do |row| -%>
      <tr>
        <% row.each do |val| -%>
          <td>
            <%= val.value || t('.no_data') %>
          </td>
        <% end -%>
      </tr>
    <% end -%>
  </tbody>
</table>