config/routes.rb
SueGlobal::Application.routes.draw do
  get "university_users/index"

  get "university_users/destroy"

  filter :locale, :pagination

  get 'index/confirm/:slug', to: 'index_confirmation#confirm', as: :index_confirm
  get 'index/reject/:slug', to: 'index_confirmation#reject', as: :index_reject
  get "annual_report/:type/(:year)", to: 'annual_report#show', as: :annual_resume

  get "summary/(:year)", to: 'summary#index', as: :summary

  resources :journals
  resources :annual_reports

  get "/pages/:id" => "pages#show", as: :page, format: false
  get "accept_change_request/:token", to: "university_change_request#accept", as: "accept_change_request"

  resources :announcements

  resources :sources
  resources :indices do
    resources :samples, shallow: true
  end
  resources :segmentation_variables, except: [:destroy] do
    resources :segments, only: [:new, :create]
  end

  resources :password_resets, only: [:create, :update, :edit]
  resources :user_sessions

  match 'login' => 'user_sessions#new', as: :login
  match 'logout' => 'user_sessions#destroy', as: :logout

  get 'signup' => 'users#new', as: 'signup'
  resources :users do
    member do
      get :activate, as: :activate
      get :roles, as: :roles, to: 'users#roles'
      post :roles, as: :roles, to: 'users#set_roles'
    end
  end

  get 'studies/:type', to: 'studies#show', as: 'studies_by_type'
  get 'studies/:type/annual_report/(:year)', to: 'annual_report#show', as: 'studies_annual_report'
  get 'activities/search', to: 'activities#search', as: 'activities_search'
  post 'activities/search', to: 'activities#retrieve', as: 'activities_search'
  resources :universities do
    resources :services, shallow: true, except: :show
    resources :achieved_activities, shallow: true
    resources :general_frames, shallow: true do
      collection do
         get 'evolution', as: :evolution
      end
    end

    resources :student_studies, shallow: true
    resources :employer_studies, shallow: true
    resources :public_source_studies, shallow: true
    resources :agreement_source_studies, shallow: true
    resources :database_studies, shallow: true
    resources :other_studies, shallow: true

    resources :users,  only: [:index, :destroy], controller: 'university_users'

    member do
      get 'add_user'
      post 'add_user', action: 'do_add_user'
    end
  end

  root to: 'pages#show', id: 'home'

end

app/models/general_frame.rb
# -*- encoding : utf-8 -*-
class GeneralFrame < ActiveRecord::Base
  include UniversityDependentModel

  GRADUATES = [:degree_graduates, :bachelors_degree_graduates, :graduates,
        :master_graduates, :phd_graduates, :specific_qualifications_graduates]

  QUALIFICATIONS = [:number_of_degrees, :number_of_bachelor_degrees,
        :number_of_qualifications, :number_of_masters_degree,
        :number_of_phds, :number_of_specific_qualifications]

  attr_accessible *GRADUATES
  attr_accessible *QUALIFICATIONS
  attr_accessible *(GRADUATES.map {|x| :"#{x}_check"})
  attr_accessible *(QUALIFICATIONS.map {|x| :"#{x}_check"})

  attr_accessible :year, :number_of_campus,
    :number_of_campus_check

  (GRADUATES | QUALIFICATIONS | [:number_of_campus]).each do |grad_field|
    attr_accessible grad_field

    define_method(grad_field) do
      super() || 0
    end

    validates grad_field,
      presence: true,
      numericality: { only_integer: true,
                      greater_than_or_equal_to: 0,
                      :if => (-> { self[:"#{grad_field}_check"] })}
  end

  validates :year,
    numericality: {only_integer: true, greater_than_or_equal_to: 0},
    presence: true

  def any_graduate_data?
    GRADUATES.map{|field| self[:"#{field}_check"]}.any?
  end

  def any_qualification_data?
    QUALIFICATIONS.map{|field| self[:"#{field}_check"]}.any?
  end

  def column_for_slug
    "general_frame_#{year}_#{year+1}"
  end

  scope :year, ->(year) { where(year: year) }
end

app/controllers/general_frames_controller.rb
# -*- encoding : utf-8 -*-
class GeneralFramesController < UniversityDependentModelController
  dependent_model :general_frame

  skip_before_filter :require_login, only: [:evolution]
  skip_load_and_authorize_resource :general_frame, only: [:evolution]
  # GET /general_frames
  # GET /general_frames.json
  def index
    @general_frames = @university.general_frames.page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @general_frames }
    end
  end

  # GET /general_frames/1
  # GET /general_frames/1.json
  def show
    @university = UniversityDecorator.decorate @general_frame.university
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @general_frame }
    end
  end

  # GET /general_frames/new
  # GET /general_frames/new.json
  def new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @general_frame }
    end
  end

  # GET /general_frames/1/edit
  def edit
    @university = UniversityDecorator.decorate @general_frame.university
  end

  # POST /general_frames
  # POST /general_frames.json
  def create
    respond_to do |format|
      if @general_frame.save
        format.html { redirect_to @general_frame, notice: t2('create.notice') }
        format.json { render json: @general_frame, status: :created, location: @general_frame }
      else
        format.html { render action: "new" }
        format.json { render json: @general_frame.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /general_frames/1
  # PUT /general_frames/1.json
  def update
    @university = UniversityDecorator.decorate @general_frame.university
    respond_to do |format|
      if @general_frame.update_attributes(params[:general_frame])
        format.html { redirect_to @general_frame, notice: t2('update.notice') }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @general_frame.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /general_frames/1
  # DELETE /general_frames/1.json
  def destroy
    @university = UniversityDecorator.decorate @general_frame.university
    @general_frame.destroy

    respond_to do |format|
      format.html { redirect_to @general_frame.university, notice: t2('destroy.notice') }
      format.json { head :no_content }
      format.js { render partial: 'destroy_animation', locals: { resource: @general_frame } }
    end
  end

  def evolution
    @university = UniversityDecorator.find_by_slug(params[:university_id])
    @evolution = GeneralFrameEvolution.new @university
    respond_to do |format|
      format.html
    end
  end

  protected
  def t2 path
    I18n.t path, scope: 'controllers.general_frames'
  end
end

app/helpers/general_frames_helper.rb
# -*- encoding : utf-8 -*-
module GeneralFramesHelper

  def numeric_field_for(field, form)
    content_tag :div, :class => 'field' do
      concat form.label(field)
      concat form.number_field(field, min: 0)
    end
  end

  def optional_numeric_field_for(field, form, content_tag_name=:div)
    content_tag :div, :class => 'field' do
      options = {}
      options.merge!({ checked: true }) if action_name == 'new'
      concat form.input("#{field}_check",
                        wrapper: :checkbox,
                        label_html: {:class => 'checkbox'},
                        input_html: {:class => 'js-other-change js-optional-numeric'})
      concat(content_tag(:span, :class => 'js-other-collapsable other-description') do
        concat form.input(field, label: false, input_html: {min: 0})
      end)
    end
  end

  def data_for(resource, field)
    content_tag :li, :class => 'field' do
      concat content_tag :span, GeneralFrame.human_attribute_name(field), :class => 'data-label'
      concat content_tag :span, resource.send(field), :class => 'data'
    end
  end
end

app/views/general_frames/_form.html.erb
<%= simple_form_for(@path) do |f| %>
  <% if @general_frame.errors.any? %>
    <div id="error_explanation">
      <h2><%= t '.errors_header', count: @general_frame.errors.count %></h2>

      <ul>
      <% @general_frame.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="explanation"><%= t('.explanation') %></div>

  <%= f.input :year,
    collection: @university.miss_general_frame_years(@general_frame),
    as: :course %>

  <%= optional_numeric_field_for :number_of_campus, f %>

  <fieldset class="graduates">
    <legend><%= t '.graduates.legend' %></legend>
    <p class="explanation"><%= t ('.graduates.explanation') %></p>
    <ol class="options">
      <% GeneralFrame::GRADUATES.each do |field| -%>
        <%= optional_numeric_field_for field, f, :li %>
      <% end -%>
    </ol>
  </fieldset>

  <fieldset class="qualifications">
    <legend><%= t '.qualifications.legend' %></legend>
    <ol class="options">
      <% GeneralFrame::QUALIFICATIONS.each do |field| -%>
        <%= optional_numeric_field_for field, f, :li %>
      <% end -%>
    </ol>
  </fieldset>

  <%= f.button :submit %>
<% end %>

app/views/general_frames/edit.html.erb
<h1>
  <%= t '.header' %>
  <%= show_link general_frame_path(@general_frame) %>
</h1>

<%= render 'form' %>

app/views/general_frames/evolution.html.erb
<h2><%= t '.title', university: @university.abbreviation %></h2>
<div id="graduates-chart" class="chart"></div>
<div id="qualifications-chart" class="chart"></div>
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">
  google.load('visualization', "1", {packages: ["corechart"]});
  $(function() {
      google.setOnLoadCallback(drawChart);
      function drawChart() {
      var gData = google.visualization.arrayToDataTable(<%= raw @evolution.graduates_data_table.to_s %>);
      var qData = google.visualization.arrayToDataTable(<%= raw @evolution.qualifications_data_table.to_s %>);

      var gChart = new google.visualization.LineChart(document.getElementById('graduates-chart'));
      var qChart = new google.visualization.LineChart(document.getElementById('qualifications-chart'));

      var options = {
        legend: {position: 'top'},
        chartArea: {width: '75%', height: '75%'}
      }
      gChart.draw(gData, options);
      qChart.draw(qData, options);
      }
  })
</script>

app/views/general_frames/index.html.erb
<h1>
  <%= t('.header', university: @university.abbreviation) %>
  <% if can? :edit, @university -%>
    <%= new_link new_university_general_frame_path(@university) %>
  <% end -%>
</h1>

<table class="table table-hover">
  <tr>
    <th><%= GeneralFrame.human_attribute_name :year %></th>
    <th><%= t('.actions') %></th>
  </tr>

<% @general_frames.each do |general_frame| %>
  <%= content_tag_for :tr, general_frame do %>
    <td><%= link_to general_frame.year, general_frame %></td>
    <td>
      <% if can? :edit, general_frame -%>
        <%= edit_link edit_general_frame_path(general_frame) %>
      <% end -%>
      <% if can? :destroy, general_frame -%>
        <%= destroy_link  general_frame,
                          method: :delete,
                          data: { confirm: t('.destroy_confirmation')} %>
      <% end -%>
    </td>
  <% end -%>
<% end %>
</table>

<br />

<%= paginate @general_frames %>

<% if can? :new, GeneralFrame -%>
    <%= link_to t('.new_general_frame'), new_university_general_frame_path(@university), class: 'btn' %>
<% end -%>

<%= link_to t('.evolucion'), evolution_university_general_frames_path(@university), class: 'btn' %>

app/views/general_frames/show.html.erb
<h1>
  <%= t '.header', university: @university.abbreviation, year: @general_frame.year %>
  <% if can? :edit, @general_frame -%>
    <%= edit_link edit_general_frame_path(@general_frame) %>
  <% end -%>
</h1>

<% if @general_frame.number_of_campus_check -%>
  <div class="field">
    <span class="data-label"><%= GeneralFrame.human_attribute_name(:number_of_campus) %></span>
    <span class="data"><%= @general_frame.number_of_campus %></span>
  </div>
<% else -%>
  <p><%= t '.no_campus_data' %></p>
<% end -%>

<% ["graduates", "qualifications"].each do |section| -%>
  <div class="<%= section %>">
    <h3><%= t ".#{section}" %></h3>
    <% if @general_frame.send(:"any_#{section.singularize}_data?") -%>
      <ul>
        <% GeneralFrame::const_get(section.upcase).each do |field| -%>
          <% if @general_frame.send(:"#{field}_check") -%>
            <%= data_for @general_frame, field %>
          <% end -%>
        <% end -%>
      </ul>
    <% else -%>
      <p><%= t ".no_#{section}_data" %></p>
    <% end -%>
  </div>
<% end -%>