config/routes.rb
SueGlobal::Application.routes.draw do
  get "university_users/index"

  get "university_users/destroy"

  filter :locale, :pagination

  get 'index/confirm/:slug', to: 'index_confirmation#confirm', as: :index_confirm
  get 'index/reject/:slug', to: 'index_confirmation#reject', as: :index_reject
  get "annual_report/:type/(:year)", to: 'annual_report#show', as: :annual_resume

  get "summary/(:year)", to: 'summary#index', as: :summary

  resources :journals
  resources :annual_reports

  get "/pages/:id" => "pages#show", as: :page, format: false
  get "accept_change_request/:token", to: "university_change_request#accept", as: "accept_change_request"

  resources :announcements

  resources :sources
  resources :indices do
    resources :samples, shallow: true
  end
  resources :segmentation_variables, except: [:destroy] do
    resources :segments, only: [:new, :create]
  end

  resources :password_resets, only: [:create, :update, :edit]
  resources :user_sessions

  match 'login' => 'user_sessions#new', as: :login
  match 'logout' => 'user_sessions#destroy', as: :logout

  get 'signup' => 'users#new', as: 'signup'
  resources :users do
    member do
      get :activate, as: :activate
      get :roles, as: :roles, to: 'users#roles'
      post :roles, as: :roles, to: 'users#set_roles'
    end
  end

  get 'studies/:type', to: 'studies#show', as: 'studies_by_type'
  get 'studies/:type/annual_report/(:year)', to: 'annual_report#show', as: 'studies_annual_report'
  get 'activities/search', to: 'activities#search', as: 'activities_search'
  post 'activities/search', to: 'activities#retrieve', as: 'activities_search'
  resources :universities do
    resources :services, shallow: true, except: :show
    resources :achieved_activities, shallow: true
    resources :general_frames, shallow: true do
      collection do
         get 'evolution', as: :evolution
      end
    end

    resources :student_studies, shallow: true
    resources :employer_studies, shallow: true
    resources :public_source_studies, shallow: true
    resources :agreement_source_studies, shallow: true
    resources :database_studies, shallow: true
    resources :other_studies, shallow: true

    resources :users,  only: [:index, :destroy], controller: 'university_users'

    member do
      get 'add_user'
      post 'add_user', action: 'do_add_user'
    end
  end

  root to: 'pages#show', id: 'home'

end

app/models/segmentation_variable.rb
# -*- encoding : utf-8 -*-
class SegmentationVariable < ActiveRecord::Base
  attr_accessible :name, :segmentation_variable_values_attributes

  validates :name,
    presence: true

  has_many :segmentation_variable_values,
    order: '"order" ASC'

  has_many :segments,
    order: '"name" ASC'

  after_create :create_total_segment

  accepts_nested_attributes_for :segmentation_variable_values

  default_scope do
    order('name ASC').includes(:segments)
  end
  def clean_update_attributes attrs
    update_attributes clean_attributes(attrs)
  end

  def clean_attributes attrs
    variable_values = attrs["segmentation_variable_values_attributes"]
    if variable_values
      new_values = segmentation_variable_values.inject({}) do |memo, obj|
        memo.tap do |m|
          memo[obj.id.to_s] = variable_values[obj.id.to_s] if variable_values.has_key? obj.id.to_s
        end
      end
      attrs["segmentation_variable_values_attributes"] = new_values
    end
    attrs
  end

  include FriendlyId
  friendly_id :name, use: :slugged

  def should_generate_new_friendly_id?
    new_record? || self[:slug].blank?
  end

  def to_key
    [slug]
  end

  def create_total_segment
    segments.build.tap do |s|
      s.name = 'Total'
      s.segmentation_variable_values = segmentation_variable_values
      s.save
    end
  end
  class << self

    def for_check_boxes
      self.all.map do |var|
        [var.id, "#{var.name} (#{var.segmentation_variable_values.count})"]
      end
    end
  end
end

app/controllers/segmentation_variables_controller.rb
# -*- encoding : utf-8 -*-
class SegmentationVariablesController < IndexRelatedModelController
  load_and_authorize_resource :segmentation_variable, only: [:index]
  related_model :segmentation_variable
  # GET /segmentation_variables
  # GET /segmentation_variables.json
  def index
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @segmentation_variables }
    end
  end

  # GET /segmentation_variables/1
  # GET /segmentation_variables/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @segmentation_variable }
    end
  end

  # GET /segmentation_variables/new
  # GET /segmentation_variables/new.json
  def new
    @segmentation_variable.segmentation_variable_values.build order: 1
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @segmentation_variable }
    end
  end

  # GET /segmentation_variables/1/edit
  def edit
  end

  # POST /segmentation_variables
  # POST /segmentation_variables.json
  def create
    respond_to do |format|
      if @segmentation_variable.save
        format.html { redirect_to @segmentation_variable, notice: t2('create.notice') }
        format.json { render json: @segmentation_variable, status: :created, location: @segmentation_variable }
      else
        format.html { render action: "new" }
        format.json { render json: @segmentation_variable.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /segmentation_variables/1
  # PUT /segmentation_variables/1.json
  def update
    respond_to do |format|
      if @segmentation_variable.clean_update_attributes(params[:segmentation_variable])
        format.html { redirect_to root_path, notice: t2('update.notice') }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @segmentation_variable.errors, status: :unprocessable_entity }
      end
    end
  end

  # Not routed.
  def destroy
    @segmentation_variable.destroy

    respond_to do |format|
      format.html { redirect_to segmentation_variables_url, notice: t2('destroy.notice') }
      format.json { head :no_content }
    end
  end

  protected
  def t2 path
    I18n.t path, scope: 'controllers.segmentation_variables'
  end
end

app/helpers/segmentation_variables_helper.rb
# -*- encoding : utf-8 -*-
module SegmentationVariablesHelper
end

app/views/segmentation_variables/_form.html.erb
<%= simple_form_for(@segmentation_variable) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, as: :string %>

    <fieldset class="segmentation_variable_values">
      <legend><%= t '.values' %></legend>
      <%= f.simple_fields_for :segmentation_variable_values do |builder| %>
        <%= render 'segmentation_variable_value_form', f: builder %>
      <% end -%>
      <% if @segmentation_variable.new_record? -%>
        <%= link_to_add_fields t('.add_value'), f, :segmentation_variable_values %>
      <% end -%>
    </fieldset>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/segmentation_variables/index.html.erb
<h1>
   <%= t '.header' %>
   <% if can? :new, SegmentationVariable -%>
     <%= new_link new_segmentation_variable_path -%>
   <% end -%>
</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th><%= SegmentationVariable.model_name.human count: 1 %></th>
      <th><%= SegmentationVariable.human_attribute_name :segmentation_variable_values_count %></th>
      <th><%= t '.actions' %></th>
    </tr>
  </thead>

  <tbody>
    <% @segmentation_variables.each do |variable| %>
      <%= content_tag_for :tr, variable do %>
      <td>
        <%= link_to variable.name, variable %>
      </td>
      <td>
         <%= variable.segmentation_variable_values.count %>
      </td>
      <td>
        <ul class="actions">
          <% if can? :edit, variable -%>
            <li><%= edit_link edit_segmentation_variable_path(variable) %>
          <% end -%>
        </ul>
      </td>
      <% end -%>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to_if can?(:new, SegmentationVariable), t('.new_variable'), new_segmentation_variable_path, :class => 'btn' do "" end %>

app/views/segmentation_variables/show.html.erb
<h1>
  <%= SegmentationVariable.model_name.human count: 1 %>
  <% if can? :edit, @segmentation_variable -%>
    <%= edit_link edit_segmentation_variable_path(@segmentation_variable) %>
  <% end -%>
</h1>

<h2><%= @segmentation_variable.name %></h2>

<h3><%= t('.values') %>:</h3>
<ol class="segmentation_variable_values">
  <% @segmentation_variable.segmentation_variable_values.each do |value| -%>
    <li><%= value.value %></li>
  <% end -%>
</ol>

<h3><%= t '.segments.header' %>:</h3>

<% if @segmentation_variable.segments.any? -%>
  <ol class="segmentation_variable_segments">
    <%= render partial: 'segment', collection: @segmentation_variable.segments %>
  </ol>
<% else -%>
  <p><%= t 'segments.none' %></p>
<% end -%>

<% if can? :new, @segmentation_variable.segments.build -%>
  <%= link_to t('.segments.new'), new_segmentation_variable_segment_path(@segmentation_variable), :class => 'btn' %>
<% end -%>